const $=s=>document.querySelector(s);
const desktop=$('#desktop'),win=$('#window'),body=$('#windowBody'),title=$('#windowTitle');
let stage=0,selected=new Set(),startedAt=Date.now();
const hints=['送信元、急かす文章、URL、添付ファイルを順番に確認しよう。','同じ文字列が設定されているサービスを探そう。','誰が管理しているか分からない接続は避けよう。','他人に見られる・使われると困るものを選ぼう。','確認コードやパスワードは、知っている相手にも共有しない。','09:12から09:24までの出来事を時刻順に追おう。'];
const guidance=['メールには4つの不審点があります。見た目だけで信用しないでください。','1つのパスワード流出が、どこまで広がるか確認しましょう。','外出先で重要資料を扱う場合の接続先を選んでください。','離席前の机を安全な状態にしてください。','相手の表示名ではなく、依頼内容で判断しましょう。','集めた記録をつなぎ、侵入経路を特定してください。'];

setInterval(()=>{const d=new Date();$('#clock').textContent=d.toLocaleTimeString('ja-JP',{hour12:false});$('#taskClock').textContent=d.toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'});},1000);
function openWindow(name){win.classList.remove('hidden');$('#notification').classList.remove('show');$('#notification').classList.add('hidden');$('#mailBadge').style.display='none';
 if(name==='mail')showMail(); else if(name==='assistant')body.innerHTML='<div class="install-view"><img src="assets/AI.png" width="130"><h2>ハタンボAI</h2><p>現在、端末に異常はありません。研修メールを確認してください。</p></div>'; else body.innerHTML='<div class="install-view"><h2>このアプリは研修では使用しません</h2><p>メールアプリから研修を開始してください。</p></div>';}
function showMail(){title.textContent='MAIL / INBOX';body.innerHTML=`<div class="mail-head"><h2>【要対応】セキュリティ研修用ソフトのご案内</h2><div class="sender"><span>情報システム部 &lt;training@mirai-support.example.com&gt;</span><span>17:30</span></div></div><div class="mail-content"><p>社員各位</p><p>本日中に新しいセキュリティ研修を完了してください。以下のリンクから研修ソフトをインストールできます。</p><p><b>未完了の場合、社内アカウントを停止します。</b></p><button class="install" id="installBtn">研修ソフトをインストール</button><p style="color:#79909f;font-size:11px">添付：security_training_setup.zip</p></div>`;$('#installBtn').onclick=install;}
function install(){body.innerHTML='<div class="install-view"><p class="puzzle-number">TRAINING SETUP</p><h2>研修ソフトをインストール中</h2><p>ファイルを検証しています…</p><div class="loader"><i></i></div></div>';setTimeout(infect,2600)}
function infect(){win.classList.add('hidden');desktop.classList.add('infected');$('#infection').classList.remove('hidden');$('#statusCopy').textContent='警告：不正なプロセスを検出しました。';const field=$('#popupField');for(let i=0;i<14;i++){const p=document.createElement('div');p.className='virus-popup';p.style.left=(4+Math.random()*76)+'%';p.style.top=(22+Math.random()*58)+'%';p.innerHTML='<header>SECURITY ERROR</header><p>ファイルが暗号化されました。<br>ERROR CODE: '+Math.random().toString(16).slice(2,8).toUpperCase()+'</p><button>OK</button>';field.appendChild(p)}}
$('#callAssistant').onclick=()=>{$('#infection').classList.add('hidden');$('#mission').classList.remove('hidden');renderPuzzle()};
function renderPuzzle(){selected=new Set();$('#progressLabel').textContent=`${stage} / 6`;$('#progressBar').style.width=`${stage/6*100}%`;$('#assistantText').textContent=guidance[stage]||'復旧処理を開始します。';const a=$('#puzzleArea');
 const views=[p1,p2,p3,p4,p5,p6];if(stage<6)a.innerHTML=views[stage]();else finish();bindPuzzle();}
function shell(n,t,c){return `<span class="puzzle-number">INVESTIGATION ${String(n).padStart(2,'0')} / 06</span><h2>${t}</h2><p class="lead">${c}</p>`}
function p1(){return shell(1,'届いたメールの異常を探せ','怪しい箇所を4つ選択してください。')+`<div class="email-card"><p>From: <button class="suspicious" data-key="from">security@mirai-support.example.com</button></p><p>件名：アカウント停止のお知らせ</p><p><button class="suspicious" data-key="rush">30分以内に確認しない場合、停止します。</button></p><p>表示URL：portal.mirai.example.com<br>移動先：<button class="suspicious" data-key="url">mirai-login.example.com</button></p><p>添付：<button class="suspicious" data-key="file">account_check.zip</button></p></div><div class="answer-row"><button data-check="select4">4か所を確認</button></div><p class="feedback"></p>`}
function p2(){return shell(2,'使い回された鍵','同じパスワードを設定した3つのサービスを選択してください。')+`<table class="password-table"><tr><th>サービス</th><th>架空の設定例</th></tr>${[['勤怠管理','BlueBird26!','a'],['ファイル共有','BlueBird26!','b'],['社内ポータル','BlueBird26!','c'],['会議予約','Desk#8194','x']].map(r=>`<tr><td><button class="suspicious" data-key="${r[2]}">${r[0]}</button></td><td><code>${r[1]}</code></td></tr>`).join('')}</table><div class="answer-row"><button data-check="reuse">選択を確認</button></div><p class="feedback"></p>`}
function p3(){return shell(3,'外出先の接続','重要な社内資料を確認するとき、最も安全な接続先を選択してください。')+`<div class="guide-card">会社ガイド：提供元を確認できないネットワークを避け、会社が認めた安全な接続方法を利用すること。</div><div class="choice-grid"><button class="choice" data-choice="bad">🔓 Cafe_Free</button><button class="choice" data-choice="bad">🔓 SHOP-WIFI</button><button class="choice" data-choice="good">🔒 会社支給スマートフォン</button><button class="choice" data-choice="bad">🔓 Cafe_Guest</button></div><p class="feedback"></p>`}
function p4(){return shell(4,'10分間の離席','席を離れる前に対応すべきものを4つ選んでください。')+`<div class="choice-grid"><button class="choice suspicious" data-key="pc">🖥 PCをロック</button><button class="choice suspicious" data-key="doc">📄 顧客書類を収納</button><button class="choice suspicious" data-key="id">🪪 社員証を携帯</button><button class="choice suspicious" data-key="memo">📝 パスワード付箋を撤去</button><button class="choice suspicious" data-key="cup">☕ コーヒー</button><button class="choice suspicious" data-key="pen">🖊 ボールペン</button></div><div class="answer-row"><button data-check="desk">安全確認</button></div><p class="feedback"></p>`}
function p5(){return shell(5,'確認コードの要求','田中さんを名乗る相手から「急ぎで確認コードを教えて」と届きました。')+`<div class="email-card"><b>田中</b><p>外出中でログインできません。届いた6桁の確認コードを送ってください。急ぎです！</p></div><div class="choice-grid"><button class="choice" data-choice="bad">今回だけコードを送る</button><button class="choice" data-choice="good">共有せず正規の手段で本人確認</button><button class="choice" data-choice="bad">自分のパスワードも送る</button><button class="choice" data-choice="bad">別のチャットでコードを送る</button></div><p class="feedback"></p>`}
function p6(){return shell(6,'侵入経路を特定せよ','不審アクセス直前の記録をつなぎ、原因を選択してください。')+`<div class="data-card"><p>09:12　研修メール受信</p><p>09:18　メール内リンクで認証情報入力</p><p>09:21　通常ログイン</p><p style="color:#ff6b83">09:24　通常と異なるログインを検知</p><p>12:25　外部ネットワーク接続</p><p>15:10　離席</p></div><div class="choice-grid"><button class="choice" data-choice="good">偽メールから認証情報を入力した</button><button class="choice" data-choice="bad">昼休みにカフェへ行った</button><button class="choice" data-choice="bad">会議室へ移動した</button><button class="choice" data-choice="bad">チャットを受信した</button></div><p class="feedback"></p>`}
function bindPuzzle(){document.querySelectorAll('.suspicious').forEach(b=>b.onclick=()=>{b.classList.toggle('selected');selected.has(b.dataset.key)?selected.delete(b.dataset.key):selected.add(b.dataset.key)});document.querySelectorAll('[data-check]').forEach(b=>b.onclick=()=>{let ok=b.dataset.check==='select4'?['from','rush','url','file'].every(x=>selected.has(x))&&selected.size===4:b.dataset.check==='reuse'?['a','b','c'].every(x=>selected.has(x))&&selected.size===3:['pc','doc','id','memo'].every(x=>selected.has(x))&&selected.size===4;result(ok)});document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>result(b.dataset.choice==='good',b));}
function result(ok,button){const f=$('.feedback');if(!ok){f.textContent='その選択では復旧ログを取得できません。画面内の情報を確認してください。';if(button)button.classList.add('wrong');return}if(button)button.classList.add('correct');f.style.color='#55ffc2';f.textContent='✓ 正解。セキュリティログを取得しました。';setTimeout(()=>{stage++;renderPuzzle()},850)}
$('#hintButton').onclick=()=>{if(stage<6)$('#assistantText').textContent='ヒント：'+hints[stage]};
function finish(){const sec=Math.floor((Date.now()-startedAt)/1000);$('#progressLabel').textContent='6 / 6';$('#progressBar').style.width='100%';$('#assistantText').textContent='すべての証拠が揃いました。端末は安全な状態へ復旧しました。';$('#puzzleArea').innerHTML=`<div class="success-panel"><span class="puzzle-number">RECOVERY COMPLETE</span><h2>端末の復旧に成功</h2><p>復旧パスワード</p><div class="recovery-code">VERIFY-6</div><p>クリアタイム ${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}</p><div class="knowledge-list"><div>📧 送信元・URL・添付を確認</div><div>🔑 パスワードを使い回さない</div><div>🌐 安全な接続を選ぶ</div><div>💻 離席時はPCをロック</div><div>👤 認証情報を共有しない</div><div>🛡 急かされてもまず確認</div></div><button class="next-button" onclick="location.reload()">最初からプレイ</button></div>`}
document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openWindow(b.dataset.open));$('#notification').onclick=()=>openWindow('mail');$('#closeWindow').onclick=()=>win.classList.add('hidden');
